### ISSUE TITLE
Issue when running docker image

### ISSUE THREAD

**Issue by jhagege** [VikParuchuri/apartment-finder#21]
Thanks for this amazing tutorial ! 
I tried running it with the Docker image but without success.

When having a look at the logs, as per your instructions in the troubleshooting, this is what I get:

```
/usr/local/lib/python3.4/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 1 of the file main_loop.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Fri Jan  5 08:44:44 2018: Starting scrape cycle
/usr/local/lib/python3.4/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 11 of the file main_loop.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Fri Jan  5 08:45:03 2018: Got 0 results
Fri Jan  5 08:45:03 2018: Successfully finished scraping
tail: unrecognized file system type 0x794c7630 for ‘/opt/wwc/logs/afinder.log’. please report this to bug-coreutils@gnu.org. reverting to polling
^[[A^C
root@a3bb6b996683:/opt/wwc/apartment-finder# tail -f -n 1000 /opt/wwc/logs/afinder.log
/usr/local/lib/python3.4/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 1 of the file main_loop.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Fri Jan  5 08:44:44 2018: Starting scrape cycle
/usr/local/lib/python3.4/dist-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 11 of the file main_loop.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Fri Jan  5 08:45:03 2018: Got 0 results
Fri Jan  5 08:45:03 2018: Successfully finished scraping
tail: unrecognized file system type 0x794c7630 for ‘/opt/wwc/logs/afinder.log’. please report this to bug-coreutils@gnu.org. reverting to polling
```

Not sure you have the resources to update it, but thought you'd like to know ;-)
Thanks !

**Comment by davidrpoliti** [comment]
I've got the same issue

**Comment by mbettan** [comment]
I solved the issue here https://github.com/mbettan/apartment-finder
You will have to rebuild the image with my change in requirements.txt
docker build -t apt .

**Comment by rudo-t** [comment]
Current issue:

Not sure whether to build my own clist scraper or tackle fixing this
`Traceback (most recent call last):
  File "main_loop.py", line 1, in <module>
    from scraper import do_scrape
  File "/opt/wwc/apartment-finder/scraper.py", line 8, in <module>
    from slackclient import SlackClient
  File "/usr/local/lib/python3.4/dist-packages/slackclient/__init__.py", line 1, in <module>
    from .client import SlackClient # noqa
  File "/usr/local/lib/python3.4/dist-packages/slackclient/client.py", line 8, in <module>
    from .server import Server
  File "/usr/local/lib/python3.4/dist-packages/slackclient/server.py", line 14, in <module>
    from websocket import create_connection
  File "/usr/local/lib/python3.4/dist-packages/websocket/__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "/usr/local/lib/python3.4/dist-packages/websocket/_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 34, in <module>
    from ._handshake import *
  File "/usr/local/lib/python3.4/dist-packages/websocket/_handshake.py", line 40, in <module>
    if six.PY34:
AttributeError: 'module' object has no attribute 'PY34'`
